# Kuantum Hesaplama: Matris, Kapılar ve Algoritmalar

Bu proje, kuantum programlamanın temelini oluşturan matris işlemlerine ve kuantum kapılarına odaklanmaktadır. Kuantum hesaplamanın matematiksel yönünü anlamak, kuantum dünyasının kapılarından geçmenin anahtarıdır. Bu proje, kuantum programlama ile ilgilenen herkes için matris teorisi ve kuantum kapılarının derinlemesine bir analizini sağlamayı amaçlamaktadır.

Projemizde, matris işlemlerinin kuantum dünyasındaki rolünü anlamak için gerekli matematiksel temelleri ele alıyoruz. Ardından, kübitlerin ve kuantum kapılarının matrislerle nasıl etkileşime girdiğini inceliyoruz. Bu projede aşağıdaki konuları vurguluyoruz:

Kuantum Programlamada Matrislerin Rolü: Kuantum hesaplamanın temel taşı olan matrislerin nasıl kullanıldığı ve kuantum durumlarını nasıl temsil ettiği.
Kuantum Kapılarının Matematiksel Temelleri: Kuantum kapılarının matris gösterimleri ve kübit durumları üzerindeki etkileri.
Uygulamalı Örnekler ve Algoritmalar: Matris işlemlerini ve kuantum kapılarını gerçek dünya problemlerine nasıl uygulayabileceğinizi gösteren örnekler ve algoritmalar.

<font color="blue">
    
İçerik:
    
1. [Matris](#1)
    * [Matrislerde Temel İşlemler: İşlemler](#2)
         
    * [Özel Matrisler](#3)

In [23]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from qiskit import *




<a id="1"></a>
## Matris

Matris matematiksel bir yapıdır ve sayıların veya sembollerin düzenli bir şekilde sıralandığı bir tablodur. Bir matris, satırlar ve sütunlar arasında oluşturulan bir düzeni ifade eder ve her hücre matrisin bir öğesini temsil eder. Matrisler çeşitli matematiksel hesaplamalar ve uygulamalar için kullanılır.

Bir matris örneği:

[ 2 4 6 ]<br>
[ 1 3 5 ]<br>
[ 7 8 9 ]

Matrisler boyutlarına göre 2x2, 3x3, 4x4 olarak ifade edilir. Örneğin yukarıdaki matris 3x3 boyutundadır.

Özellikle şimdi inceleyeceğimiz konu olan Kuantum Hesaplama: Kuantum hesaplamada da matrisler sıklıkla kullanılmaktadır.

  Bunun dışında :

* Doğrusal Denklemler ve Sistemler: Matrisler doğrusal denklemleri temsil etmek ve denklem sistemlerini çözmek için kullanılır.

* Grafik Tasarım ve Görüntü İşleme: Matrisler, görüntülerin piksel değerlerini ve renklerini temsil etmek için kullanılır.

* Veri Analizi ve İstatistik: Matrisler veri setlerini temsil etmek, analiz etmek ve düzenlemek için kullanılır.

* Mühendislik ve Fizik: Matrisler dönüşümleri, ölçeklendirmeyi ve fiziksel problemleri ifade etmek için kullanılır.

    Matrisler matematik dünyasının birçok farklı alanında temel bir rol oynar ve birçok problemi daha yapılandırılmış ve anlaşılır bir şekilde ifade etmemizi sağlar.

<a id="2"></a>
### Matrislerde Temel İşlemler: İşlemler 

Matrisler, matematik dünyasında çok çeşitli uygulamaları olan temel yapı taşlarıdır. Matrisler üzerindeki işlemler, birçok alanda kullanılan işlemleri anlamamıza ve gerçek dünya problemlerini çözmemize yardımcı olur.

#### 1. Matris Toplama:

Aynı boyuttaki matrislerin elemanlarını toplarız. Her bir eleman yerine diğer matrisin aynı konumdaki elemanını ekleriz.

<table>
  <tr>
    <td>
      [[1, 2, 3]<br>
      [4, 5, 6]<br>
      [7, 8, 9]]
    </td>
    <td style="padding: 10px;">+</td>
    <td>
      [[9, 8, 7]<br>
      [6, 5, 4]<br>
      [3, 2, 1]]
    </td>
    <td style="padding: 10px;">=</td>
    <td>
      [[10, 10, 10]<br>
      [10, 10, 10]<br>
      [10, 10, 10]]
    </td>
  </tr>
</table> 


In [24]:
def matrix_addition(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]

result = matrix_addition(matrix1, matrix2)
print("Matris Toplamı:")
for row in result:
    print(row)

Matris Toplamı:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]





#### 2. Matris Çarpımı:

Matrislerin çarpımı, satır ve sütun elemanlarının uygun şekilde çarpılması ve toplanması ile hesaplanır.

<table>
  <tr>
    <td>
      [[1, 2]<br>
      [3, 4]]
    </td>
    <td style="padding: 10px;">*</td>
    <td>
      [[5, 6]<br>
      [7, 8]]
    </td>
    <td style="padding: 10px;">=</td>
    <td>
      [[19, 22]<br>
      [43, 50]]
    </td>
  </tr>
  </table>


Çarpma işlemi için sonuç matrisinin boyutları birinci matrisin satır sayısına ve ikinci matrisin sütun sayısına eşittir. Yani sonuç matrisi 2x2 boyutunda olacaktır.<br><br>


Sonuç matrisinin ilk elemanını hesaplamak için:
[ 1 * 5 + 2 * 7 ] = [ 19 ]

Sonuç matrisinin ikinci elemanını hesaplamak için:
[ 1 * 6 + 2 * 8 ] = [ 22 ]

Sonuç matrisinin üçüncü elemanını hesaplamak için:
[ 3 * 5 + 4 * 7 ] = [ 43 ]

Sonuç matrisinin dördüncü elemanını hesaplamak için:
[ 3 * 6 + 4 * 8 ] = [ 50 ]

In [25]:
def matrix_multiplication(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            sum = 0
            for k in range(len(matrix2)):
                sum += matrix1[i][k] * matrix2[k][j]
            row.append(sum)
        result.append(row)
    return result

matrix1 = [[1, 2],
           [3, 4]]

matrix2 = [[5, 6],
           [7, 8]]

result = matrix_multiplication(matrix1, matrix2)
print("Matris çarpımı:")
for row in result:
    print(row)

Matris çarpımı:
[19, 22]
[43, 50]


#### 3. Matris Skaler Çarpımı:

Bir matrisin bir sayı ile çarpılması, tüm elemanlarının o sayı ile çarpılması anlamına gelir.

<table>
  <tr>
    <td>
      [[1, 2, 3]<br>
      [4, 5, 6]<br>
      [7, 8, 9]]
    </td>
    <td style="padding: 10px;">×</td>
    <td>
      2
    </td>
    <td style="padding: 10px;">=</td>
    <td>
      [[2, 4, 6]<br>
      [8, 10, 12]<br>
      [14, 16, 18]]
    </td>
  </tr>
</table>

Bir matrisin tüm elemanlarını bir skaler (sayı) ile çarpmak, yeni bir matris oluşturmak için her bir elemanı bu skaler değerle çarpmak anlamına gelir.

Sonuç matrisinin ilk satırını hesaplamak için: [ 1 * 2 , 2 * 2 , 3 * 2 ]<br>


Sonuç matrisinin ikinci satırını hesaplamak için: [ 4 * 2 , 5 * 2 , 6 * 2 ]<br>


Sonuç matrisinin üçüncü satırını hesaplamak için: [ 7 * 2 , 8 * 2 , 9 * 2 ]

In [26]:
def matrix_scalar_multiplication(matrix, scalar):
    result = []
    for i in range(len(matrix)):
        row = []
        for j in range(len(matrix[0])):
            row.append(matrix[i][j] * scalar)
        result.append(row)
    return result

matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

scalar = 2

result = matrix_scalar_multiplication(matrix, scalar)
print(f"{scalar} Çarpılmış Matris:")
for row in result:
    print(row)

2 Çarpılmış Matris:
[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


<a id="3"></a>
#### Özel Matrisler

##### Birim (kare) Matrisi (I)
Birim matris olarak da bilinen özdeşlik matrisi, kare matrisin özel bir türüdür. Köşegen elemanlarının tümü 1 (bir) ve diğer tüm elemanlarının tümü 0 (sıfır) olan bir matristir. Genellikle "I" veya "E" sembolleri ile gösterilir. Özdeşlik matrisi, matris çarpımında nötr bir eleman olarak işlev görür. Yani herhangi bir matrisi özdeşlik matrisi ile çarptığınızda sonuç olarak aynı matris elde edilir.

3x3 boyutunda özdeşlik matrisi örneği aşağıdaki gibidir:

[ 1 0 0 ] <br>
[ 0 1 0 ]<br>
[ 0 0 1 ]

Özdeşlik matrisi, matris teorisi ve lineer cebirde çok önemli bir rol oynar. Matrislerin tersinin bulunması, doğrusal denklemlerin çözülmesi ve dönüşüm matrislerinin oluşturulması gibi birçok uygulama alanında kullanılır.

In [27]:
def create_identity_matrix(size):
    identity_matrix = []
    for i in range(size):
        row = []
        for j in range(size):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        identity_matrix.append(row)
    return identity_matrix

size = 3  # İstediğiniz boyutu burada belirtebilirsiniz.
identity_matrix = create_identity_matrix(size)

for row in identity_matrix:
    print(row)

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


##### Ters Matris

Ters matris, lineer cebirde temel bir kavramdır ve bir kare matrisin tersidir. A matrisinin tersi A-¹ olarak gösterilir ve orijinal A matrisi ile çarpıldığında birim matris I'yı verir:

A * A-¹ = I

Bir matrisin tersi, matris sonsuz olmadığında (determinantı sıfır olmadığında) bulunur. Ters matrisler doğrusal denklem sistemlerini çözmek, dönüşümleri gerçekleştirmek ve diğer birçok amaç için kullanılır.

In [28]:
# Matrisi tanımla
matrix = np.array([[1, 2],
                   [3, 4]])

# Tersini hesaplayın
ters_matris = np.linalg.inv(matrix)

print("Orijinal Matris:")
print(matrix)

print("\nTers Matris:")
print(ters_matris)

Orijinal Matris:
[[1 2]
 [3 4]]

Ters Matris:
[[-2.   1. ]
 [ 1.5 -0.5]]


##### Transpoze

Bir matrisin transpozesi, matrisin satırlarını sütunlarla değiştiren bir işlemdir. Elde edilen matris, orijinal matrisin transpozu olarak adlandırılır. Orijinal matris A ile gösteriliyorsa, transpozu A^T veya A' ile gösterilir.

Matematiksel olarak, A m x n boyutlu bir matris ise, transpozu A^T n x m boyutlu bir matristir ve A'nın i. satır ve j. sütunundaki eleman A^T matrisindeki j. satırın i. sütunundaki elemandır.

Daha basit bir ifadeyle, orijinal matrisin satırları transpoze matrisin sütunları olur ve orijinal matrisin sütunları transpoze matrisin satırları olur.

In [29]:
# Matris Tanımla
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transpozeyi hesapla
transpose_matrix = np.transpose(matrix)

print("Orjinal Matris:")
print(matrix)

print("\nTranspoze Matris:")
print(transpose_matrix)

Orjinal Matris:
[[1 2 3]
 [4 5 6]]

Transpoze Matris:
[[1 4]
 [2 5]
 [3 6]]


##### Kompleks Eşlenik (Complex Conjugate)

Matrislerde "karmaşık eşlenik" terimi, matrisin her bir elemanı karmaşık bir sayı olduğunda, her bir elemanın eşlenik karmaşık sayısının alınmasıyla oluşturulan yeni bir matrisi ifade eder.

<table>
  <tr>
    <td>3 + 2i</td>
    <td>1 - 5i</td>
  </tr>
  <tr>
    <td>7 + 9i</td>
    <td>4 + 6i</td>
  </tr>
</table>


<table border="1">
  <tr>
    <td>3 - 2i</td>
    <td>1 + 5i</td>
  </tr>
  <tr>
    <td>7 - 9i</td>
    <td>4 - 6i</td>
  </tr>
</table>

Eşlenik transpoze veya Hermitian transpoze olarak da bilinen bir matrisin eşlenik transpozesi, iki adımdan oluşan matematiksel bir işlemdir: önce matrisin transpozesini almak, ardından her bir elemanın karmaşık eşleniğini almak.

Eğer A bir matris ise, onun adjoint transpozu A^† veya A^H olarak gösterilir. Bu işlemde, önce A matrisinin transpozu alınır, daha sonra her bir elemanın karmaşık eşleniği alınır.

Matematiksel olarak, eğer A m x n boyutunda bir matris ise, o zaman A^† adjoint transpozu n x m boyutunda bir matristir ve A^† matrisinin i. satır ve j. sütunundaki eleman, A matrisinin j. satır ve i. sütunundaki elemanın karmaşık eşleniğidir.

Daha basit bir ifadeyle, orijinal matrisin satırları adjoint transpoze matrisin sütunları haline gelir ve her bir elemanın karmaşık eşleniği alınır.

In [30]:
# Matris Tanımla
matrix = np.array([[1+2j, 3-4j],
                   [5+6j, 7-8j]])

# Eşlenik transpozeyi hesaplayın
adjoint_transpose_matrix = np.conjugate(np.transpose(matrix))

print("Orijinal Matris:")
print(matrix)

print("\nEşlenik Transpoze Matrisi:")
print(adjoint_transpose_matrix)

Orijinal Matris:
[[1.+2.j 3.-4.j]
 [5.+6.j 7.-8.j]]

Eşlenik Transpoze Matrisi:
[[1.-2.j 5.-6.j]
 [3.+4.j 7.+8.j]]


##### Üniter Matrisi (Unitery Matrix)

Üniter matris veya birim matris, lineer cebirde önemli bir kavramdır. Bir matrisin üniter olması, eşlenik transpozesinin (Hermitian transpozesi) tersine eşit olduğu anlamına gelir.

Matematiksel olarak, eğer A matrisi üniter ise, aşağıdaki koşul sağlanmış demektir:
A * A^† = A^† * A = I

Burada A matrisi A^† matrisinin tersine eşittir ve I kimlik matrisidir.

Üniter matrisler çeşitli matematiksel ve fiziksel uygulamalarda kullanılır. Özellikle kuantum mekaniği ve dalga teorisinde yaygındırlar.

In [31]:
# 2x2'lik bir matris tanımlayın
matrix = np.array([[1j, 1],
                   [1, -1j]])

# Eşlenik transpozeyi al
adjoint_transpose = np.conjugate(np.transpose(matrix))

# Matrisi adjoint transpozesi ile çarpın
product = np.dot(matrix, adjoint_transpose)

# Sonuçları yazdır
print("Orijinal Matris:")
print(matrix)

print("\nEşlenik Transpoze Matrisi:")
print(adjoint_transpose)

print("\nÜrün Matris:")
print(product)

Orijinal Matris:
[[ 0.+1.j  1.+0.j]
 [ 1.+0.j -0.-1.j]]

Eşlenik Transpoze Matrisi:
[[ 0.-1.j  1.-0.j]
 [ 1.-0.j -0.+1.j]]

Ürün Matris:
[[ 2.+0.j -0.+2.j]
 [ 0.-2.j  2.+0.j]]


##### Hermiyon matrisi (Hermitian Matrix)

Bir matrisin Hermitian (öz eşlenik veya öz simetrik) olması, matris transpoze edildiğinde her bir elemanın karmaşık eşleniği ile aynı olduğu anlamına gelir<br>
A^† = A

In [32]:
# Bir Hermitian matris tanımlayın
matrix = np.array([[3 + 2j, 1 - 5j],
                   [1 + 5j, 4 + 6j]])

# Matrisin transpozesini alın ve karmaşık eşleniğini hesaplayın
transpose = np.transpose(matrix)
conjugate = np.conjugate(matrix)

# Matrisin Hermitian olup olmadığını kontrol edin
is_hermitian = np.allclose(transpose, conjugate)

# Sonuçları yazdır
print("Orijinal Matrix:")
print(matrix)

print("\nTranspoze Matris:")
print(transpose)

print("\nKarmaşık Eşlenik Matris:")
print(conjugate)

if is_hermitian:
    print("\nMatris Hermitian'dır.")
else:
    print("\nMatris Hermitian değildir.")

Orijinal Matrix:
[[3.+2.j 1.-5.j]
 [1.+5.j 4.+6.j]]

Transpoze Matris:
[[3.+2.j 1.+5.j]
 [1.-5.j 4.+6.j]]

Karmaşık Eşlenik Matris:
[[3.-2.j 1.+5.j]
 [1.-5.j 4.-6.j]]

Matris Hermitian değildir.


##### Vektör

Kuantum bilgisayarlarda vektörler kübitlerin durumlarını temsil etmek için kullanılır. Kuantum hesaplamada vektörler ve matrisler, kübit durumlarını ve kuantum kapılarının etkileşimini anlamada önemli bir rol oynar.