# Quantum Computing: Matrix, Gates and Algorithms

This project focuses on matrix operations and quantum gates, which form the basis of quantum programming. Understanding the mathematical aspect of quantum computing is the key to traversing the gates of the quantum world. This project aims to provide an in-depth analysis of matrix theory and quantum gates for anyone interested in quantum programming.

In our project, we cover the mathematical foundations necessary to understand the role of matrix operations in the quantum world. Then, we study how qubits and quantum gates interact with matrices. In this project, we emphasise the following topics:

The Role of Matrices in Quantum Programming: How matrices, the cornerstone of quantum computation, are used and how they represent quantum states.
Mathematical Foundations of Quantum Gates: Matrix representations of quantum gates and their effects on qubit states.
Hands-on Examples and Algorithms: Examples and algorithms that show how you can apply matrix operations and quantum gates to real-world problems.

<font color="blue">
    
Content:
    
1. [Matrix](#1)
    * [Basic Operations in Matrices: Operations](#2)
         
    * [Special Matrix](#3)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from qiskit import *

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

<a id="1"></a>
## Matrix

What is a Matrix?

A matrix is a mathematical structure and is a table in which numbers or symbols are arranged in an orderly manner. A matrix refers to a layout created between rows and columns, and each cell represents an element of the matrix. Matrices are used for various mathematical calculations and applications.

Example of a matrix:

[ 2 4 6 ]<br>
[ 1 3 5 ]<br>
[ 7 8 9 ]

 Matrices are expressed as 2x2, 3x3, 4x4 depending on their size. For example, the matrix above is of size 3x3.

Especially Quantum Computing, which is the subject we will examine now: Matrices are also frequently used in quantum computing.

  Apart from this :

* Linear Equations and Systems: Matrices are used to represent linear equations and solve systems of equations.

* Graphic Design and Image Processing: Matrices are used to represent pixel values and colours of images.

* Data Analysis and Statistics: Matrices are used to represent, analyse and organise data sets.

* Engineering and Physics: Matrices are used to express transformations, scaling and physical problems.

    Matrices play a fundamental role in many different areas of the mathematical world and allow us to express many problems in a more structured and understandable way.


<a id="2"></a>
### Basic Operations in Matrices: Operations 

Matrices are fundamental building blocks with a wide range of applications in the mathematical world. Operations on matrices help us understand operations used in many fields and solve real-world problems.

#### 1. Matrix Summation:

We add the elements of matrices of the same size. Instead of each element, we add the element of the other matrix in the same position.


 <table>
  <tr>
    <td>
      [[1, 2, 3]<br>
      [4, 5, 6]<br>
      [7, 8, 9]]
    </td>
    <td style="padding: 10px;">+</td>
    <td>
      [[9, 8, 7]<br>
      [6, 5, 4]<br>
      [3, 2, 1]]
    </td>
    <td style="padding: 10px;">=</td>
    <td>
      [[10, 10, 10]<br>
      [10, 10, 10]<br>
      [10, 10, 10]]
    </td>
  </tr>
</table> 


In [2]:
def matrix_addition(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]

result = matrix_addition(matrix1, matrix2)
print("Matrix Sum:")
for row in result:
    print(row)

Matrix Sum:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


#### 2. Matrix Multiplication:

Multiplication of matrices is calculated by multiplying and adding the row and column elements appropriately.

<table>
  <tr>
    <td>
      [[1, 2]<br>
      [3, 4]]
    </td>
    <td style="padding: 10px;">*</td>
    <td>
      [[5, 6]<br>
      [7, 8]]
    </td>
    <td style="padding: 10px;">=</td>
    <td>
      [[19, 22]<br>
      [43, 50]]
    </td>
  </tr>
</table>
For multiplication, the dimensions of the result matrix are equal to the number of rows of the first matrix and the number of columns of the second matrix. So the result matrix will be of size 2x2.<br><br>


To calculate the first element of the result matrix:
[ 1 * 5 + 2 * 7 ] = [ 19 ]

To calculate the second element of the result matrix:
[ 1 * 6 + 2 * 8 ] = [ 22 ]

To calculate the third element of the result matrix:
[ 3 * 5 + 4 * 7 ] = [ 43 ]

To calculate the fourth element of the result matrix:
[ 3 * 6 + 4 * 8 ] = [ 50 ]

In [3]:
def matrix_multiplication(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            sum = 0
            for k in range(len(matrix2)):
                sum += matrix1[i][k] * matrix2[k][j]
            row.append(sum)
        result.append(row)
    return result

matrix1 = [[1, 2],
           [3, 4]]

matrix2 = [[5, 6],
           [7, 8]]

result = matrix_multiplication(matrix1, matrix2)
print("Matrix Multiplication:")
for row in result:
    print(row)

Matrix Multiplication:
[19, 22]
[43, 50]


#### 3. Matrix Scalar Multiplication:

Multiplying a matrix by a number means multiplying all its elements by that number.

<table>
  <tr>
    <td>
      [[1, 2, 3]<br>
      [4, 5, 6]<br>
      [7, 8, 9]]
    </td>
    <td style="padding: 10px;">×</td>
    <td>
      2
    </td>
    <td style="padding: 10px;">=</td>
    <td>
      [[2, 4, 6]<br>
      [8, 10, 12]<br>
      [14, 16, 18]]
    </td>
  </tr>
</table>

Multiplying all elements of a matrix by a scalar (number) means multiplying each element by this scalar value to create a new matrix.


To calculate the first row of the result matrix: [ 1 * 2 , 2 * 2 , 3 * 2 ]<br>


To calculate the second row of the result matrix: [ 4 * 2 , 5 * 2 , 6 * 2 ]<br>


To calculate the third row of the result matrix: [ 7 * 2 , 8 * 2 , 9 * 2 ]

In [4]:
def matrix_scalar_multiplication(matrix, scalar):
    result = []
    for i in range(len(matrix)):
        row = []
        for j in range(len(matrix[0])):
            row.append(matrix[i][j] * scalar)
        result.append(row)
    return result

matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

scalar = 2

result = matrix_scalar_multiplication(matrix, scalar)
print(f"{scalar} Multiplied Matrix:")
for row in result:
    print(row)

2 Multiplied Matrix:
[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


<a id="3"></a>
#### Special Matrix

##### Identıty Matrix (I)
Identity matrix, also known as unit matrix, is a special type of square matrix. It is a matrix whose diagonal elements are all 1 (one) and all other elements are all 0 (zero). It is usually denoted by the symbols "I" or "E". Identity matrix acts as a neutral element in matrix multiplication. So when you multiply any matrix by identity matrix, the same matrix is obtained as a result.

Identity matrix example in 3x3 size is as follows:


[ 1 0 0 ] <br>
[ 0 1 0 ]<br>
[ 0 0 1 ]

Identity matrix plays a very important role in matrix theory and linear algebra. It is used in many application areas such as finding the inverse of matrices, solving linear equations and constructing transformation matrices.

In [5]:
def create_identity_matrix(size):
    identity_matrix = []
    for i in range(size):
        row = []
        for j in range(size):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        identity_matrix.append(row)
    return identity_matrix

size = 3  # You can specify the desired size here.
identity_matrix = create_identity_matrix(size)

for row in identity_matrix:
    print(row)

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


##### Inverse Matrix

The inverse matrix is a fundamental concept in linear algebra and is the inverse of a square matrix. The inverse of matrix A is denoted as A-¹, which when multiplied by the original matrix A gives the unit matrix I:

A * A-¹ = I

The inverse of a matrix is found when the matrix is non-indefinite (its determinant is non-zero). Inverse matrices are used to solve systems of linear equations, to perform transformations and for many other purposes.

In [6]:
# Define matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Calculate the reverse
ters_matris = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(ters_matris)

Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


##### Transpose

The transpose of a matrix is an operation that replaces the rows of the matrix with columns. The resulting matrix is called the transpose of the original matrix. If the original matrix is denoted by A, its transpose is denoted by A^T or A'.

Mathematically, if A is a matrix of dimension m x n, then its transpose A^T is a matrix of dimension n x m and the element in row i and column j of A is the element in column i of row j in the matrix A^T.

In simpler terms, the rows of the original matrix become the columns of the transposed matrix and the columns of the original matrix become the rows of the transposed matrix.

In [7]:
# Define the matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Calculate the transpose
transpose_matrix = np.transpose(matrix)

print("Original Matrix:")
print(matrix)

print("\nTranspose Matrix:")
print(transpose_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]]

Transpose Matrix:
[[1 4]
 [2 5]
 [3 6]]


##### Complex Conjugate

In matrices, the term "complex conjugate" refers to a new matrix formed by taking the conjugate complex number of each element when each element of the matrix is a complex number.



<table>
  <tr>
    <td>3 + 2i</td>
    <td>1 - 5i</td>
  </tr>
  <tr>
    <td>7 + 9i</td>
    <td>4 + 6i</td>
  </tr>
</table>


<table border="1">
  <tr>
    <td>3 - 2i</td>
    <td>1 + 5i</td>
  </tr>
  <tr>
    <td>7 - 9i</td>
    <td>4 - 6i</td>
  </tr>
</table>

The adjoint transpose of a matrix, also known as conjugate transpose or Hermitian transpose, is a mathematical operation that consists of two steps: first taking the transpose of the matrix, then taking the complex conjugate of each element.

If A is a matrix, its adjoint transpose is denoted A^† or A^H. In this operation, first the transpose of matrix A is taken, then the complex conjugate of each element is taken.

Mathematically, if A is a matrix of dimension m x n, then the adjoint transpose A^† is a matrix of dimension n x m and the element in row i and column j of matrix A^† is the complex conjugate of the element in row j and column i of matrix A.

In simpler terms, the rows of the original matrix become the columns of the adjoint transpose matrix and the complex conjugate of each element is taken.

In [8]:
# Define the matrix
matrix = np.array([[1+2j, 3-4j],
                   [5+6j, 7-8j]])

# Calculate the adjoint transpose
adjoint_transpose_matrix = np.conjugate(np.transpose(matrix))

print("Original Matrix:")
print(matrix)

print("\nAdjoint Transpose Matrix:")
print(adjoint_transpose_matrix)

Original Matrix:
[[1.+2.j 3.-4.j]
 [5.+6.j 7.-8.j]]

Adjoint Transpose Matrix:
[[1.-2.j 5.-6.j]
 [3.+4.j 7.+8.j]]


##### Unitery Matrix

Unitary matrix, or unit matrix, is an important concept in linear algebra. For a matrix to be unitary means that its adjoint transpose (Hermitian transpose) is equal to its inverse.

Mathematically, if matrix A is unitary, the following condition is satisfied:
A * A^† = A^† * A = I

Here the matrix A is equal to the inverse of the matrix A^† and I is the identity matrix.

Unitary matrices are used in various mathematical and physical applications. They are especially common in quantum mechanics and wave theory.

In [9]:
# Define a 2x2 matrix
matrix = np.array([[1j, 1],
                   [1, -1j]])

# Take the adjoint transpose
adjoint_transpose = np.conjugate(np.transpose(matrix))

# Multiply the matrix by its adjoint transpose
product = np.dot(matrix, adjoint_transpose)

# Print the results
print("Original Matrix:")
print(matrix)

print("\nAdjoint Transpose Matrix:")
print(adjoint_transpose)

print("\nProduct Matrix:")
print(product)

Original Matrix:
[[ 0.+1.j  1.+0.j]
 [ 1.+0.j -0.-1.j]]

Adjoint Transpose Matrix:
[[ 0.-1.j  1.-0.j]
 [ 1.-0.j -0.+1.j]]

Product Matrix:
[[ 2.+0.j -0.+2.j]
 [ 0.-2.j  2.+0.j]]


##### Hermitian Matrix

For a matrix to be Hermitian (eigenadjoint or eigensymmetric) means that when the matrix is transposed, each element is identical to its complex conjugate:<br>
A^† = A

In [10]:
# Define a Hermitian matrix
matrix = np.array([[3 + 2j, 1 - 5j],
                   [1 + 5j, 4 + 6j]])

# Take the transpose of the matrix and calculate its complex conjugate
transpose = np.transpose(matrix)
conjugate = np.conjugate(matrix)

# Check if the matrix is Hermitian
is_hermitian = np.allclose(transpose, conjugate)

# Print the results
print("Original Matrix:")
print(matrix)

print("\nTranspose Matrix:")
print(transpose)

print("\nComplex Conjugate Matrix:")
print(conjugate)

if is_hermitian:
    print("\nThe matrix is Hermitian.")
else:
    print("\nThe matrix is not Hermitian.")

Original Matrix:
[[3.+2.j 1.-5.j]
 [1.+5.j 4.+6.j]]

Transpose Matrix:
[[3.+2.j 1.+5.j]
 [1.-5.j 4.+6.j]]

Complex Conjugate Matrix:
[[3.-2.j 1.+5.j]
 [1.-5.j 4.-6.j]]

The matrix is not Hermitian.


##### Vector

In quantum computers, vectors are used to represent the states of qubits. In quantum computing, vectors and matrices play an important role in understanding qubit states and the interaction of quantum gates.